@ECHO OFF
CD /D "%~DP0"
XCOPY ..\DEBUG\*.EXE x86\BACKUP\ /A /H /K /V /Y
XCOPY ..\DEBUG\*.SYS x86\BACKUP\ /A /H /K /V /Y
XCOPY ..\DEBUG\*.DLL x86\BACKUP\ /A /H /K /V /Y
XCOPY ..\DEBUG\*.MP3 x86\BACKUP\ /A /H /K /V /Y
XCOPY ..\x64\DEBUG\*.EXE x64\BACKUP\ /A /H /K /V /Y
XCOPY ..\x64\DEBUG\*.SYS x64\BACKUP\ /A /H /K /V /Y
XCOPY ..\x64\DEBUG\*.DLL x64\BACKUP\ /A /H /K /V /Y
XCOPY ..\x64\DEBUG\*.MP3 x64\BACKUP\ /A /H /K /V /Y
PAUSE
EXIT /B